# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "part", # <get_corpus>
  "index", # <plot_snowball>
  "cited_by_count_by_year", # <plot_snowball>
  "type", # <plot_snowball>
  "oa_input", # <plot_snowball>
  "auth_abbr", # <plot_snowball>
  "cairo_pdf", # <plot_snowball>
  "cited_by_count", # <plot_snowball>
  "Freq", # <to_data_frame>
  "Var1", # <to_data_frame>
  "id", # <to_data_frame>
  "publication_year", # <to_data_frame>
  "cited_by_count", # <to_data_frame>
  "years_published", # <to_data_frame>
  "avg_citations_per_year", # <to_data_frame>
  "author", # <to_data_frame>
  "display_name", # <to_data_frame>
  "doi", # <to_data_frame>
  "so", # <to_data_frame>
  "ab", # <to_data_frame>
  "cited_global", # <to_data_frame>
  "Freq", # <to_xlsx>
  "Var1", # <to_xlsx>
  "id", # <to_xlsx>
  "publication_year", # <to_xlsx>
  "cited_by_count", # <to_xlsx>
  "years_published", # <to_xlsx>
  "avg_citations_per_year", # <to_xlsx>
  "display_name", # <to_xlsx>
  "doi", # <to_xlsx>
  "ab", # <to_xlsx>
  "level", # <to_xlsx>
  "score", # <to_xlsx>
  "name", # <to_xlsx>
  "author", # <to_xlsx>
  "cited_global", # <to_xlsx>
  "cited_global_per_year", # <to_xlsx>
  "no_connections", # <to_xlsx>
  "abstract", # <to_xlsx>
  "concepts_l0", # <to_xlsx>
  "concepts_l1", # <to_xlsx>
  "concepts_l2", # <to_xlsx>
  "concepts_l3", # <to_xlsx>
  "concepts_l4", # <to_xlsx>
  "concepts_l5", # <to_xlsx>
  "author_institute", # <to_xlsx>
  "institute_country", # <to_xlsx>
  NULL
))
